app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@Login');
Route::get('auth/logout', 'Auth\AuthController@getLogout');



Route::get('/', function() {
    //$user = Auth::user();
    // dd($user->name);
    if (Auth::check()) {
        // The user is logged in...
        Auth::logout();
        //echo 'some one is loged';
    }

    return view('pages/auth/login');
});




Route::group(['middleware' => 'auth'], function () {

     //dd($_POST);
    /* Route::any('welcome', function() {
      //$user = Auth::user();
      // dd($user->name);


      return view('pages/home');
      }); */

    Route::resource('welcome', 'welcomeController');

    Route::get('calendar', 'CalendarController@calendar');

    Route::get('reservation_calender', 'CalendarController@av_calendar');

    /* Route::get('calendar', function() {
      //$user = Auth::user();
      // dd($user->name);

      return view('pages/calendar/calendar');
      }); */

    Route::resource('hotel_page', 'HotelController');

    Route::resource('room_type', 'RoomTypeController');

    Route::resource('room', 'RoomController');

    Route::resource('guest_page', 'GuestController');

    Route::resource('reservation_page', 'ReservationController');


    /* Route::any('reservation_calender', function() {
      //$user = Auth::user();
      // dd($user->name);
      return view('pages/reservation_details/reservation_calender');
      }); */


    Route::resource('room_map', 'RoomMapController');


    Route::any('room_detail/{roomDetail}', 'RoomMapController@view_single_room_details');



    /* Route::any('room_detail/{roomDetail}', function($roomDetail) {

      $myString = $roomDetail;
      $myArray = explode('"', $myString);

      dd($myArray[3]);


      return view('pages/room_details/roomMap/single_room_map_detail',  compact('roomDetail'));
      }); */

    //////////sytem settings////////////////////////
    //dd($_POST);
    Route::resource('system_user_setting', 'SystemUserController');
});

app/Http/Controllers/RoomTypeController.php
<?php

namespace App\Http\Controllers;

//use Illuminate\Http\Request;

use Request;
use App\Models\RoomType;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class RoomTypeController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        //
        $roomTypes = RoomType::all();
        return view('pages.room_details.roomType.room_type_page', compact('roomTypes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //        
        return view('pages.room_details.roomType.room_type_add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //
        $roomTypes = Request::all();
        RoomType::create($roomTypes);
        return redirect('room_type');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
        $room_type = RoomType::find($id);
        return view('pages.room_details.roomType.room_type_show', compact('room_type'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        //
        $room_type = RoomType::find($id);
        return view('pages.room_details.roomType.room_type_update', compact('room_type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
        $roomTypeUpdate = Request::all();
        $roomType = RoomType::find($id);
        $roomType->update($roomTypeUpdate);
        return redirect('room_type');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
        RoomType::find($id)->delete();
        return redirect('room_type');
    }

}

resources/views/pages/room_details/roomType/room_type_add.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection


@section('content')

<section class="content-header">
    <h1>Room Type Add <small>page </small></h1>
</section><hr/>

<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">

            {!! Form::open(['url' => 'room_type']); !!}
            <div>
                <div class="form-group">
                    {!! Form::label('type_name', 'Room Type Name: '); !!}
                    <div class="form-controls">                     
                        {!! Form::text('typeName', null, ['class' => 'form-control', 'id' => 'code', 'placeholder' => 'Enter Room Type Name']); !!}
                    </div>
                </div>


                <div class="form-group">
                    {!! Form::label('type_descriptin', 'Type Description : '); !!}
                    <div class="form-controls">                     
                        {!! Form::textarea('typeDescription', null, ['class' => 'form-control', 'id' => 'typeDescription', 'placeholder' => 'Enter Room Type Description ']); !!}
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <p id='buttons'>
                    {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!} &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
                    {!! Form::reset('Cancel', ['class' => 'btn btn-default']) !!}
                </p>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</section>



<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("room_menu");
    document.getElementById("room_menu").className = "active";
    var slide_bar_element = document.getElementById("rm2_submenu");
    document.getElementById("rm2_submenu").className = "active";
</script>


@endsection

resources/views/pages/room_details/roomType/room_type_page.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection

@section('content')




<section class="content-header">
    <h1>Room Type  Details <small>page </small></h1>
</section>


<br/>

<!-- Main content -->
<section class="content fluid">
    <div class="row">
        <div class="box box-warning">
            <div class="gap">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <col width='auto'>
                        <col width='auto'>
                        <col width='100'>

                        <thead>
                            <tr>
                                <th>Room ID</th>
                                <th>Room Type Name</th>
                                <th><p id='buttons'> <a href="{{ route('room_type.create')}}" class="btn btn-success"> <strong> Add Room Types &nbsp </strong> <span class="glyphicon glyphicon-plus"></span> </a> </p></th>
                        </tr>
                        </thead>
                        <tbody>                  
                            @foreach($roomTypes as $roomType)
                            <tr>
                                <td><a href="{{route('room_type.show', $roomType->id)}}"> {{ $roomType->id }} </a></td>        
                                <td><a href="{{route('room_type.show', $roomType->id)}}"> {{ $roomType->typeName }} </a></td>                                   
                                <td align='center'>
                                    {!! Form::open(['method' => 'DELETE', 'route'=>['room_type.destroy',$roomType->id]]) !!}
                                    <a href="{{route('room_type.edit',$roomType->id)}}" class="btn btn-default btn-sm"> <span class="glyphicon glyphicon-pencil"></span> </a> &nbsp &nbsp
                                    <button type="submit" class="btn btn-default btn-sm" onclick="return confirm('Are you sure?')"> <span class="glyphicon glyphicon-trash"></span> </button> 
                                    {!! Form::close() !!}
                                </td> 
                            </tr>
                            @endforeach

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Room ID</th>
                                <th>Room Type Name</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div><!-- /.row -->
</section><!-- /.content -->

<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("room_menu");
    document.getElementById("room_menu").className = "active";
    var slide_bar_element = document.getElementById("rm2_submenu");
    document.getElementById("rm2_submenu").className = "active";
</script>

@endsection

resources/views/pages/room_details/roomType/room_type_show.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection

@section('content')



<section class="content-header">
    <h1>Hotel  Room Type View <small> page </small></h1>
</section>


<br/>
<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">
            {!! Form::open(['method' => 'DELETE', 'route' => ['room_type.destroy', $room_type->id]]); !!}
            <a href="javascript:history.go(-1)" class="btn btn-default" style='float: right;'> <span class="glyphicon glyphicon-remove-circle"></span> </a>
            <button type="submit" class="btn btn-default" onclick="return confirm('Are you sure?')" style='float: right;'> <span class="glyphicon glyphicon-trash"></span> </button>
            <a href="{!! url('room_type/'.$room_type->id.'/edit') !!}" class="btn btn-default" style='float: right;'> <span class="glyphicon glyphicon-pencil"></span> </a>
            {!! Form::close() !!}

            <br/> <hr/>

            <fieldset>
                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <label>Room Type : </label>
                        </div> 
                        <div class="col-xs-9">
                            {{ $room_type->typeName }} 
                        </div>
                    </div>
                </div>
                <br/>
                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <label>Room Type Description: </label>
                        </div> 
                        <div class="col-xs-9">
                            {{ $room_type->typeDescription }} 
                        </div>
                    </div>
                </div>
                
                <br/>
                
                
            </fieldset>
        </div>
    </div>
</section>


<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("room_menu");
    document.getElementById("room_menu").className = "active";
    var slide_bar_element = document.getElementById("rm2_submenu");
    document.getElementById("rm2_submenu").className = "active";
</script>

@endsection

resources/views/pages/room_details/roomType/room_type_update.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection


@section('content')



<section class="content-header">
    <h1>Hotel Room Type Update <small>page </small></h1>
</section><hr/>


<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">

            {!! Form::model($room_type ,['method' => 'PATCH','route'=>['room_type.update',$room_type->id]]) !!}

            <div>
                <div class="form-group">
                    {!! Form::label('type_name', 'Room Type Name: '); !!}
                    <div class="form-controls">                     
                        {!! Form::text('typeName', null, ['class' => 'form-control', 'id' => 'code', 'placeholder' => 'Enter Room Type Name']); !!}
                    </div>
                </div>


                <div class="form-group">
                    {!! Form::label('type_descriptin', 'Type Description : '); !!}
                    <div class="form-controls">                     
                        {!! Form::textarea('typeDescription', null, ['class' => 'form-control', 'id' => 'typeDescription', 'placeholder' => 'Enter Room Type Description ']); !!}
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <p id='buttons'>
                    {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!} &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
                    {!! Form::reset('Cancel', ['class' => 'btn btn-default']) !!}
                </p>
                {!! Form::close() !!}
            </div>

        </div>
</section>

<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("room_menu");
    
    document.getElementById("room_menu").className = "active";
    
    var slide_bar_element = document.getElementById("rm2_submenu");   
    document.getElementById("rm2_submenu").className = "active";
</script>



@endsection