app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@Login');
Route::get('auth/logout', 'Auth\AuthController@getLogout');



Route::get('/', function() {
    //$user = Auth::user();
    // dd($user->name);
    if (Auth::check()) {
        // The user is logged in...
        Auth::logout();
        //echo 'some one is loged';
    }

    return view('pages/auth/login');
});




Route::group(['middleware' => 'auth'], function () {

     //dd($_POST);
    /* Route::any('welcome', function() {
      //$user = Auth::user();
      // dd($user->name);


      return view('pages/home');
      }); */

    Route::resource('welcome', 'welcomeController');

    Route::get('calendar', 'CalendarController@calendar');

    Route::get('reservation_calender', 'CalendarController@av_calendar');

    /* Route::get('calendar', function() {
      //$user = Auth::user();
      // dd($user->name);

      return view('pages/calendar/calendar');
      }); */

    Route::resource('hotel_page', 'HotelController');

    Route::resource('room_type', 'RoomTypeController');

    Route::resource('room', 'RoomController');

    Route::resource('guest_page', 'GuestController');

    Route::resource('reservation_page', 'ReservationController');


    /* Route::any('reservation_calender', function() {
      //$user = Auth::user();
      // dd($user->name);
      return view('pages/reservation_details/reservation_calender');
      }); */


    Route::resource('room_map', 'RoomMapController');


    Route::any('room_detail/{roomDetail}', 'RoomMapController@view_single_room_details');



    /* Route::any('room_detail/{roomDetail}', function($roomDetail) {

      $myString = $roomDetail;
      $myArray = explode('"', $myString);

      dd($myArray[3]);


      return view('pages/room_details/roomMap/single_room_map_detail',  compact('roomDetail'));
      }); */

    //////////sytem settings////////////////////////
    //dd($_POST);
    Route::resource('system_user_setting', 'SystemUserController');
});

resources/views/pages/reservation_details/reservation_add.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection


@section('content')

<section class="content-header">
    <h1>Receive Your Dream <small>Room </small></h1>
</section><hr/>

<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">

            {!! Form::open(['url' => 'reservation_page']); !!}

            <fieldset id='myfieldset'>
                <legend> Register new  Guest </legend>

                <div>
                    <div class="form-group">
                        {!! Form::label('guest_name', 'Guest Name: '); !!}
                        <div class="form-controls">                     
                            {!! Form::text('Name', null, ['class' => 'form-control', 'id' => 'Name', 'placeholder' => 'Enter Guest Name']); !!}
                        </div>
                    </div>


                    <div class="form-group">
                        {!! Form::label('guest_nic', 'NIC :'); !!}
                        <div class="form-controls">                     
                            {!! Form::text('nic', null, ['class' => 'form-control', 'id' => 'nic', 'placeholder' => 'Enter Guest NIC ']); !!}
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset id='myfieldset'>


                <div class="form-group">
                    {!! Form::label('email', 'E-mail: '); !!}
                    <div class="form-controls">
                        {!! Form::email('email', null, ['class' => 'form-control', 'id' => 'id1', 'placeholder' => 'Enter Email Address ']); !!}
                    </div>
                </div>

                <div class='row'>
                    <div class='col-md-4'>
                        <div class="form-group">
                            {!! Form::label('telephone', 'Telephone : '); !!}
                            <div class="form-controls">
                                {!! Form::text('telephone', null, ['class' => 'form-control', 'id' => 'id4', 'placeholder' => 'Telephone ']); !!}
                            </div>
                        </div>
                    </div>
                </div>

                <hr/>

                <div>
                    <button type="submit"   class="btn btn-primary"  name="register_guest_button">Register New Guest</button>
                    <button type="reset" class="btn btn-default">Cancel</button>
                </div>


            </fieldset> 
   
            <br/>

            <fieldset id='myfieldset'>

                <legend> Reservation Details </legend>
                <!-- Date range -->
                <div class="form-group">
                    <label> Accommodate Date range:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <input type="text" class="form-control pull-right" id="reservation" name="accom_Date">
                        {!! Form::hidden('accommodateDate', null) !!}
                        {!! Form::hidden('accommodateCloseDate', null) !!}

                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <!-- Date and time range -->
                <div class="form-group">
                    <label>Check-In Check-Out  range:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-clock-o"></i>
                        </div>
                        <input type="text" class="form-control pull-right" id="reservationtime" name="check_in_out">
                        {!! Form::hidden('check_in', null) !!}
                        {!! Form::hidden('check_out', null) !!}

                    </div><!-- /.input group -->
                </div><!-- /.form group -->


                <div class="form-group">
                    {!! Form::label('no_of_members', 'No of Members'); !!}
                    <div class="form-controls">                     
                        {!! Form::number('no_of_members', null, ['class' => 'form-control', 'id' => 'no_of_members', 'placeholder' => 'No: of Members ']); !!}
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('hotelId', 'Select Your Hotel: '); !!}
                            <div class="form-controls">
                                {!! Form::select('hotelId',$hotels, null, ['class' => 'form-control' ]); !!}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('roomId', 'Room Code: '); !!}
                            <div class="form-controls">
                                {!! Form::select('roomId',$rooms, null, ['class' => 'form-control' ]); !!}
                            </div>
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('guessId', 'Guest Name : '); !!}
                            <div class="form-controls">
                                {!! Form::select('guestId', $guests, null, ['class' => 'form-control' ]); !!}
                            </div>
                        </div>                          
                    </div>
                </div>

                <hr/>


                <div>
                    <button type="submit"   class="btn btn-primary"  name="reserve_room_button">Reserve A Room</button>
                    <button type="reset" class="btn btn-default">Cancel</button>
                </div>



            </fieldset>           
            {!! Form::close() !!}         
        </div>
    </div>
</section>



<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("m_menu");
    document.getElementById("m_menu").className = "active";
    var slide_bar_element = document.getElementById("m1_submenu");
    document.getElementById("m1_submenu").className = "active";
</script>


@endsection

resources/views/pages/reservation_details/reservation_available_calendar.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection

@section('content')


<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="box box-primary">
            <div class="box-body no-padding">
                {!! $calendar->calendar() !!}
            </div><!-- /.box-body -->
        </div><!-- /. box -->
        <!-- </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->


@section('scripts')
{!! $calendar->script() !!}
@stop


<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("m_menu");
    document.getElementById("m_menu").className = "active";
    
    var slide_bar_element = document.getElementById("m3_submenu");
    document.getElementById("m3_submenu").className = "active";
</script>



@endsection

resources/views/pages/reservation_details/reservation_page.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection

@section('content')




<section class="content-header">
    <h1>Reservation Details <small>page </small></h1>
</section>


<br/>

<!-- Main content -->
<section class="content fluid">
    <div class="row">
        <div class="box box-warning">
            <div class="gap">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <col width='auto'>
                        <col width='auto'>
                        <col width='auto'>
                        <col width='auto'>
                        <col width='auto'>
                        <col width='auto'>
                        <col width='100'>

                        <thead>
                            <tr>
                                <th>Accommodate Date</th>
                                <th>Accommodate Close Date</th>
                                <th>Check In</th>
                                <th>Check Out</th>
                                <th>Members Count</th>
                                <th>Room Code</th>
                                <th><p id='buttons'> <a href="{{ route('reservation_page.create')}}" class="btn btn-success"> <strong>New Reservation &nbsp </strong> <span class="glyphicon glyphicon-plus"></span> </a> </p></th>
                        </tr>
                        </thead>
                        <tbody>                  
                            @foreach($reservations as $reservation)
                            <tr>
                                <td><a href="{{route('reservation_page.show', $reservation->id)}}"> {{ $reservation->accommodateDate }} </a></td>        
                                <td><a href="{{route('reservation_page.show', $reservation->id)}}"> {{ $reservation->accommodateCloseDate }} </a></td>        
                                <td> {{ $reservation->check_in }} </td>        
                                <td> {{ $reservation->check_out }} </td> 
                                <td> {{ $reservation->no_of_members }} </td>        
                                <td> {{ $reservation->roomId }} </td> 

                                <td align='center'>
                                    {!! Form::open(['method' => 'DELETE', 'route'=>['reservation_page.destroy',$reservation->id]]) !!}
                                    <a href="{{route('reservation_page.edit',$reservation->id)}}" class="btn btn-default btn-sm"> <span class="glyphicon glyphicon-pencil"></span> </a> &nbsp &nbsp
                                    <button type="submit" class="btn btn-default btn-sm" onclick="return confirm('Are you sure?')"> <span class="glyphicon glyphicon-trash"></span> </button> 
                                    {!! Form::close() !!}
                                </td> 
                            </tr>
                            @endforeach

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Accommodate Date</th>
                                <th>Accommodate Close Date</th>
                                <th>Check In</th>
                                <th>Check Out</th>
                                <th>Members Count</th>
                                <th>Room Code</th>                             
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div><!-- /.row -->
</section><!-- /.content -->

<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("m_menu");
    document.getElementById("m_menu").className = "active";
    var slide_bar_element = document.getElementById("m1_submenu");
    document.getElementById("m1_submenu").className = "active";
</script>

@endsection

resources/views/pages/reservation_details/reservation_show.blade.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

resources/views/pages/reservation_details/reservation_update.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection


@section('content')



<section class="content-header">
    <h1>Update Reservation <small>page </small></h1>
</section><hr/>


<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">

            {!! Form::model($reservation ,['method' => 'PATCH','route'=>['reservation_page.update',$reservation->id]]) !!}

            <fieldset id='myfieldset'>
                <!-- Date range -->
                <div class="form-group">
                    <label> Accommodate Date range:</label>
                    {!! Form::label('laccom_Date',$reservation['laccom_Date']) !!}
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <input type="text" class="form-control pull-right" id="reservation" name="accom_Date">
                        {!! Form::hidden('accommodateDate', null) !!}
                        {!! Form::hidden('accommodateCloseDate', null) !!}

                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <!-- Date and time range -->
                <div class="form-group">
                    <label>Check-In Check-Out  range:</label>
                    {!! Form::label('lcheck_in_out',$reservation['lcheck_in_out']) !!}
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-clock-o"></i>
                        </div>
                        <input type="text" class="form-control pull-right" id="reservationtime" name="check_in_out">
                        {!! Form::hidden('check_in', null) !!}
                        {!! Form::hidden('check_out', null) !!}

                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    {!! Form::label('no_of_members', 'No of Members'); !!}
                    <div class="form-controls">                     
                        {!! Form::number('no_of_members', null, ['class' => 'form-control', 'id' => 'no_of_members', 'placeholder' => 'No: of Members ']); !!}
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('hotelId', 'Select Your Hotel: '); !!}
                            <div class="form-controls">
                                {!! Form::select('hotelId',$hotels, null, ['class' => 'form-control' ]); !!}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('roomId', 'Room NO: '); !!}
                            <div class="form-controls">
                                {!! Form::select('roomId',$rooms, null, ['class' => 'form-control' ]); !!}
                            </div>
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('guessId', 'Guest Name : '); !!}
                            <div class="form-controls">
                                {!! Form::select('guestId', $guests, null, ['class' => 'form-control' ]); !!}
                            </div>
                        </div>                          
                    </div>
                </div>


            </fieldset>



            <div class="box-footer">
                <p id='buttons'>
                    {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!} &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
                    {!! Form::reset('Cancel', ['class' => 'btn btn-default']) !!}
                </p>
                {!! Form::close() !!}
            </div>

        </div>
</section>

<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("m_menu");
    document.getElementById("m_menu").className = "active";
    var slide_bar_element = document.getElementById("m1_submenu");
    document.getElementById("m1_submenu").className = "active";
</script>


@endsection