app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@Login');
Route::get('auth/logout', 'Auth\AuthController@getLogout');



Route::get('/', function() {
    //$user = Auth::user();
    // dd($user->name);
    if (Auth::check()) {
        // The user is logged in...
        Auth::logout();
        //echo 'some one is loged';
    }

    return view('pages/auth/login');
});




Route::group(['middleware' => 'auth'], function () {

     //dd($_POST);
    /* Route::any('welcome', function() {
      //$user = Auth::user();
      // dd($user->name);


      return view('pages/home');
      }); */

    Route::resource('welcome', 'welcomeController');

    Route::get('calendar', 'CalendarController@calendar');

    Route::get('reservation_calender', 'CalendarController@av_calendar');

    /* Route::get('calendar', function() {
      //$user = Auth::user();
      // dd($user->name);

      return view('pages/calendar/calendar');
      }); */

    Route::resource('hotel_page', 'HotelController');

    Route::resource('room_type', 'RoomTypeController');

    Route::resource('room', 'RoomController');

    Route::resource('guest_page', 'GuestController');

    Route::resource('reservation_page', 'ReservationController');


    /* Route::any('reservation_calender', function() {
      //$user = Auth::user();
      // dd($user->name);
      return view('pages/reservation_details/reservation_calender');
      }); */


    Route::resource('room_map', 'RoomMapController');


    Route::any('room_detail/{roomDetail}', 'RoomMapController@view_single_room_details');



    /* Route::any('room_detail/{roomDetail}', function($roomDetail) {

      $myString = $roomDetail;
      $myArray = explode('"', $myString);

      dd($myArray[3]);


      return view('pages/room_details/roomMap/single_room_map_detail',  compact('roomDetail'));
      }); */

    //////////sytem settings////////////////////////
    //dd($_POST);
    Route::resource('system_user_setting', 'SystemUserController');
});

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Room extends Model {

    //
    protected $table = 'room';
    protected $fillable = [
        //
        'room_code',
        'roomState',
        'hotelId',
        'roomTypeId'
    ];

}

app/Models/RoomType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RoomType extends Model
{
    //
    protected $table = 'roomType';
    
    protected $fillable = [
       //
        'typeName',
        'typeDescription'
    ];
    
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

//use Illuminate\Http\Request;

use Request;
use Auth;
use App\Models\Room;
use App\Models\Hotel;
use App\Models\RoomType;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use DB;

class RoomController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        //


        $user_id = Auth::user()->id;
        $hotel_id = DB::select(DB::raw("SELECT hotelId FROM user_role WHERE userId ='+$user_id+';"));
       // dd($hotel_id == []);
        if ($hotel_id != []) {
            $h_id = $hotel_id[0]->hotelId;
            $view_no;
            // dd($hotel_id[0]->hotelId);
            if ($hotel_id[0]->hotelId != null) {
                $rooms = Room::where('hotelId', '=', $h_id)->get();
                $view_no = 1;
            } else {
                $rooms = Room::all();
                $view_no = 2;
            }
        }else{
            $rooms = Room::all();
            $view_no = 2;
        }


        foreach ($rooms as $room) {

            $hotelId = DB::table('hotel')->where('id', $room->hotelId)->value('hotalName');
            $roomTypeId = DB::table('roomType')->where('id', $room->roomTypeId)->value('typeName');

            $room->hotelId = $hotelId;
            $room->roomTypeId = $roomTypeId;
        }


        return view('pages.room_details.room.room_page', compact('rooms', 'view_no'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
        $hotels = Hotel::lists('hotalName', 'id');
        $room_types = RoomType::lists('typeName', 'id');
        return view('pages.room_details.room.room_add', compact('hotels', 'room_types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //

        $rooms = Request::all();
        Room::create($rooms);
        return redirect('room');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
        $room = Room::find($id);

        $hotelId = DB::table('hotel')->where('id', $room->hotelId)->value('hotalName');
        $roomTypeId = DB::table('roomType')->where('id', $room->roomTypeId)->value('typeName');

        $room->hotelId = $hotelId;
        $room->roomTypeId = $roomTypeId;

        return view('pages.room_details.room.room_show', compact('room'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        //
        $room = Room::find($id);

        $hotels = Hotel::lists('hotalName', 'id');
        $room_types = RoomType::lists('typeName', 'id');


        return view('pages.room_details.room.room_update', compact('room', 'hotels', 'room_types'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
        $roomUpdate = Request::all();
        $room = Room::find($id);
        $room->update($roomUpdate);
        return redirect('room');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
        Room::find($id)->delete();
        return redirect('room');
    }

}

resources/views/pages/room_details/room/room_add.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection


@section('content')

<section class="content-header">
    <h1>Room Add <small>page </small></h1>
</section><hr/>

<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">

            {!! Form::open(['url' => 'room']); !!}
            <div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('room_code', 'Room Code: '); !!}
                            <div class="form-controls">
                                {!! Form::text('room_code', null, ['class' => 'form-control', 'id' => 'code', 'placeholder' => 'Enter Room Code  Here']); !!}
                            </div>
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('hotelId', 'Hotel Name: '); !!}
                            <div class="form-controls">
                                {!! Form::select('hotelId', $hotels, null, ['class' => 'form-control' ]); !!}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('roomTypeId', 'Room Type : '); !!}
                            <div class="form-controls">
                                {!! Form::select('roomTypeId', $room_types, null, ['class' => 'form-control' ]); !!}
                            </div>
                        </div>                          
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('roomState', 'Room State: '); !!}
                            <div class="form-controls">
                                {!! Form::select('roomState', ['Available'=>'Available', 'UnAvailable'=>'UnAvailable'], null, ['class' => 'form-control', 'id'=>'roomState']); !!}
                            </div>
                        </div>                          
                    </div>
                </div>


            </div>

            <div class="box-footer">
                <p id='buttons'>
                    {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!} &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
                    {!! Form::reset('Cancel', ['class' => 'btn btn-default']) !!}
                </p>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</section>



<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("room_menu");
    document.getElementById("room_menu").className = "active";
    var slide_bar_element = document.getElementById("rm1_submenu");
    document.getElementById("rm1_submenu").className = "active";
</script>


@endsection

resources/views/pages/room_details/room/room_page.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection

@section('content')




<section class="content-header">
    <h1>Room   Details <small>page </small></h1>
</section>


<br/>

<!-- Main content -->
<section class="content fluid">
    <div class="row">
        <div class="box box-warning">
            <div class="gap">
                <div class="box-body">
                    @if ($view_no == 2)
                    <table id="example1" class="table table-bordered table-striped">
                        <col width='auto'>
                        <col width='auto'>  
                        <col width='auto'>
                        <col width='auto'>
                        <col width='100'>

                        <thead>
                            <tr>
                                <th>Hotel Name</th>
                                <th>Room Code</th>
                                <th>Room Type </th>
                                <th>Room State</th>
                                <th><p id='buttons'> <a href="{{ route('room.create')}}" class="btn btn-success"> <strong> Add New Rooms &nbsp </strong> <span class="glyphicon glyphicon-plus"></span> </a> </p></th>
                        </tr>
                        </thead>
                        <tbody>                  
                            @foreach($rooms as $room)
                            <tr>
                                <td><a href="{{route('room.show', $room->id)}}"> {{ $room->hotelId }} </a></td>        
                                <td><a href="{{route('room.show', $room->id)}}"> {{ $room->room_code }} </a></td>                                  
                                <td><a href="{{route('room.show', $room->id)}}"> {{ $room->roomTypeId }} </a></td>                                   
                                <td> {{ $room->roomState }}</td>                                   
                                <td align='center'>
                                    {!! Form::open(['method' => 'DELETE', 'route'=>['room.destroy',$room->id]]) !!}
                                    <a href="{{route('room.edit',$room->id)}}" class="btn btn-default btn-sm"> <span class="glyphicon glyphicon-pencil"></span> </a> &nbsp &nbsp
                                    <button type="submit" class="btn btn-default btn-sm" onclick="return confirm('Are you sure?')"> <span class="glyphicon glyphicon-trash"></span> </button> 
                                    {!! Form::close() !!}
                                </td> 
                            </tr>
                            @endforeach

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Hotel Name</th>
                                <th>Room Code</th>
                                <th>Room Type </th>
                                <th>Room State</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                    @else
                    <table id="example1" class="table table-bordered table-striped">                       
                        <col width='auto'>  
                        <col width='auto'>
                        <col width='auto'>
                        <col width='100'>

                        <thead>
                            <tr>                       
                                <th>Room Code</th>
                                <th>Room Type </th>
                                <th>Room State</th>
                                <th><p id='buttons'> <a href="{{ route('room.create')}}" class="btn btn-success"> <strong> Add New Rooms &nbsp </strong> <span class="glyphicon glyphicon-plus"></span> </a> </p></th>
                        </tr>
                        </thead>
                        <tbody>                  
                            @foreach($rooms as $room)
                            <tr>
                                <td><a href="{{route('room.show', $room->id)}}"> {{ $room->room_code }} </a></td>                                  
                                <td><a href="{{route('room.show', $room->id)}}"> {{ $room->roomTypeId }} </a></td>                                   
                                <td> {{ $room->roomState }}</td>                                   
                                <td align='center'>
                                    {!! Form::open(['method' => 'DELETE', 'route'=>['room.destroy',$room->id]]) !!}
                                    <a href="{{route('room.edit',$room->id)}}" class="btn btn-default btn-sm"> <span class="glyphicon glyphicon-pencil"></span> </a> &nbsp &nbsp
                                    <button type="submit" class="btn btn-default btn-sm" onclick="return confirm('Are you sure?')"> <span class="glyphicon glyphicon-trash"></span> </button> 
                                    {!! Form::close() !!}
                                </td> 
                            </tr>
                            @endforeach

                        </tbody>
                        <tfoot>
                            <tr>               
                                <th>Room Code</th>
                                <th>Room Type </th>
                                <th>Room State</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                    @endif

                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div><!-- /.row -->
</section><!-- /.content -->

<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("room_menu");
    document.getElementById("room_menu").className = "active";
    var slide_bar_element = document.getElementById("rm1_submenu");
    document.getElementById("rm1_submenu").className = "active";
</script>

@endsection

resources/views/pages/room_details/room/room_show.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection

@section('content')



<section class="content-header">
    <h1>Hotel  Room  View <small> page </small></h1>
</section>


<br/>
<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">
            {!! Form::open(['method' => 'DELETE', 'route' => ['room.destroy', $room->id]]); !!}
            <a href="javascript:history.go(-1)" class="btn btn-default" style='float: right;'> <span class="glyphicon glyphicon-remove-circle"></span> </a>
            <button type="submit" class="btn btn-default" onclick="return confirm('Are you sure?')" style='float: right;'> <span class="glyphicon glyphicon-trash"></span> </button>
            <a href="{!! url('room/'.$room->id.'/edit') !!}" class="btn btn-default" style='float: right;'> <span class="glyphicon glyphicon-pencil"></span> </a>
            {!! Form::close() !!}

            <br/> <hr/>

            <fieldset>
                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <label>Hotel  Name : </label>
                        </div> 
                        <div class="col-xs-9">
                            {{ $room->hotelId }} 
                        </div>
                    </div>
                </div>
                <br/>

                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <label>Hotel  Name : </label>
                        </div> 
                        <div class="col-xs-9">
                            {{ $room->hotelId }} 
                        </div>
                    </div>
                </div>

                <br/>
                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <label>Room Code : </label>
                        </div> 
                        <div class="col-xs-9">
                            {{ $room->room_code }} 
                        </div>
                    </div>
                </div>

                <br/>

                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <label>Room State : </label>
                        </div> 
                        <div class="col-xs-9">
                            {{ $room->roomState }} 
                        </div>
                    </div>
                </div>

                <br/>

            </fieldset>
        </div>
    </div>
</section>


<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("room_menu");
    document.getElementById("room_menu").className = "active";
    var slide_bar_element = document.getElementById("rm1_submenu");
    document.getElementById("rm1_submenu").className = "active";
</script>

@endsection

resources/views/pages/room_details/room/room_update.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection


@section('content')



<section class="content-header">
    <h1>Room Details Update <small>page </small></h1>
</section><hr/>


<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">
            {!! Form::model($room ,['method' => 'PATCH','route'=>['room.update',$room->id]]) !!}
            <div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('room_code', 'Room Code: '); !!}
                            <div class="form-controls">
                                {!! Form::text('room_code', null, ['class' => 'form-control', 'id' => 'code', 'placeholder' => 'Enter Room Code  Here']); !!}
                            </div>
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('hotelId', 'Hotel Name: '); !!}
                            <div class="form-controls">
                                {!! Form::select('hotelId', $hotels, null, ['class' => 'form-control' ]); !!}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('roomTypeId', 'Room Type : '); !!}
                            <div class="form-controls">
                                {!! Form::select('roomTypeId', $room_types, null, ['class' => 'form-control' ]); !!}
                            </div>
                        </div>                          
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            {!! Form::label('roomState', 'Room State: '); !!}
                            <div class="form-controls">
                                {!! Form::select('roomState', ['Available'=>'Available', 'UnAvailable'=>'UnAvailable'], null, ['class' => 'form-control', 'id'=>'roomState']); !!}
                            </div>
                        </div>                          
                    </div>
                </div>


            </div>


            <div class="box-footer">
                <p id='buttons'>
                    {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!} &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
                    {!! Form::reset('Cancel', ['class' => 'btn btn-default']) !!}
                </p>
                {!! Form::close() !!}
            </div>

        </div>
    </div>
</section>

<script type="text/javascript" >
    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";
    var slide_bar_element = document.getElementById("room_menu");
    document.getElementById("room_menu").className = "active";
    var slide_bar_element = document.getElementById("rm1_submenu");
    document.getElementById("rm1_submenu").className = "active";
</script>

@endsection