app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@Login');
Route::get('auth/logout', 'Auth\AuthController@getLogout');



Route::get('/', function() {
    //$user = Auth::user();
    // dd($user->name);
    if (Auth::check()) {
        // The user is logged in...
        Auth::logout();
        //echo 'some one is loged';
    }

    return view('pages/auth/login');
});




Route::group(['middleware' => 'auth'], function () {

     //dd($_POST);
    /* Route::any('welcome', function() {
      //$user = Auth::user();
      // dd($user->name);


      return view('pages/home');
      }); */

    Route::resource('welcome', 'welcomeController');

    Route::get('calendar', 'CalendarController@calendar');

    Route::get('reservation_calender', 'CalendarController@av_calendar');

    /* Route::get('calendar', function() {
      //$user = Auth::user();
      // dd($user->name);

      return view('pages/calendar/calendar');
      }); */

    Route::resource('hotel_page', 'HotelController');

    Route::resource('room_type', 'RoomTypeController');

    Route::resource('room', 'RoomController');

    Route::resource('guest_page', 'GuestController');

    Route::resource('reservation_page', 'ReservationController');


    /* Route::any('reservation_calender', function() {
      //$user = Auth::user();
      // dd($user->name);
      return view('pages/reservation_details/reservation_calender');
      }); */


    Route::resource('room_map', 'RoomMapController');


    Route::any('room_detail/{roomDetail}', 'RoomMapController@view_single_room_details');



    /* Route::any('room_detail/{roomDetail}', function($roomDetail) {

      $myString = $roomDetail;
      $myArray = explode('"', $myString);

      dd($myArray[3]);


      return view('pages/room_details/roomMap/single_room_map_detail',  compact('roomDetail'));
      }); */

    //////////sytem settings////////////////////////
    //dd($_POST);
    Route::resource('system_user_setting', 'SystemUserController');
});

app/Models/Guest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Guest extends Model
{
    //
    protected $table = 'guest';
    
    protected $fillable = [
       //
        'Name',
        'nic',
        'telephone',
        'email'
        
    ];
}

app/Http/Controllers/GuestController.php
<?php

namespace App\Http\Controllers;

//use Illuminate\Http\Request;

use Request;
use App\Models\Guest;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class GuestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $guests = Guest::all();
        
        
        
        return view('pages.guest.guest_page', compact('guests'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('pages.guest.guest_add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $guests = Request::all();
        Guest::create($guests);
        return redirect('guest_page');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $guest = Guest::find($id);
        return view('pages.guest.guest_show', compact('guest'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $guest = Guest::find($id);
        return view('pages.guest.guest_update', compact('guest'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $guestUpdate = Request::all();
        $guest = Guest::find($id);
        $guest->update($guestUpdate);
        return redirect('guest_page');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Guest::find($id)->delete();
        return redirect('guest_page');
    }
}

resources/views/pages/guest/guest_add.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection


@section('content')

<section class="content-header">
    <h1>Guest Add <small>page </small></h1>
</section><hr/>

<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">

            {!! Form::open(['url' => 'guest_page']); !!}
            <fieldset id='myfieldset'>
                <legend> Basic Details </legend>

                <div>
                    <div class="form-group">
                        {!! Form::label('guest_name', 'Guest Name: '); !!}
                        <div class="form-controls">                     
                            {!! Form::text('Name', null, ['class' => 'form-control', 'id' => 'Name', 'placeholder' => 'Enter Guest Name']); !!}
                        </div>
                    </div>


                    <div class="form-group">
                        {!! Form::label('guest_nic', 'NIC :'); !!}
                        <div class="form-controls">                     
                            {!! Form::text('nic', null, ['class' => 'form-control', 'id' => 'nic', 'placeholder' => 'Enter Guest NIC ']); !!}
                        </div>
                    </div>
                </div>
            </fieldset>
            
            <fieldset id='myfieldset'>
                <legend> Contact Details </legend>

                <div class="form-group">
                    {!! Form::label('email', 'E-mail: '); !!}
                    <div class="form-controls">
                        {!! Form::email('email', null, ['class' => 'form-control', 'id' => 'id1', 'placeholder' => 'Enter Email Address ']); !!}
                    </div>
                </div>
               
                <div class='row'>
                    <div class='col-md-4'>
                        <div class="form-group">
                            {!! Form::label('telephone', 'Telephone : '); !!}
                            <div class="form-controls">
                                {!! Form::text('telephone', null, ['class' => 'form-control', 'id' => 'id4', 'placeholder' => 'Telephone ']); !!}
                            </div>
                        </div>
                    </div>
                </div>

            </fieldset> 
            
            <br>
            <div class="box-footer">
                <p id='buttons'>
                    {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!} &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
                    {!! Form::reset('Cancel', ['class' => 'btn btn-default']) !!}
                </p>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</section>



<script type="text/javascript" >

    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";

    var slide_bar_element = document.getElementById("guest_menu");
    document.getElementById("guest_menu").className = "active";

</script>


@endsection

resources/views/pages/guest/guest_page.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection

@section('content')




<section class="content-header">
    <h1>Hotel Details <small>page </small></h1>
</section>


<br/>

<!-- Main content -->
<section class="content fluid">
    <div class="row">
        <div class="box box-warning">
            <div class="gap">
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <col width='auto'>
                        <col width='auto'>
                        <col width='auto'>
                        <col width='auto'>
                        <col width='100'>

                        <thead>
                            <tr>
                                <th>Guest Name</th>
                                <th>Guest Nic</th>
                                <th>Telephone</th>
                                <th>E-mail</th>
                                <th><p id='buttons'> <a href="{{ route('guest_page.create')}}" class="btn btn-success"> <strong> Add New Guest &nbsp </strong> <span class="glyphicon glyphicon-plus"></span> </a> </p></th>
                        </tr>
                        </thead>
                        <tbody>                  
                            @foreach($guests as $guest)
                                @if($guest->id != 3)
                                <tr>
                                    <td><a href="{{route('guest_page.show', $guest->id)}}"> {{ $guest->Name }} </a></td>        
                                    <td><a href="{{route('guest_page.show', $guest->id)}}"> {{ $guest->nic }} </a></td>        
                                    <td> {{ $guest->telephone }} </td>        
                                    <td> {{ $guest->email }} </td>        

                                    <td align='center'>
                                        {!! Form::open(['method' => 'DELETE', 'route'=>['guest_page.destroy',$guest->id]]) !!}
                                        <a href="{{route('guest_page.edit',$guest->id)}}" class="btn btn-default btn-sm"> <span class="glyphicon glyphicon-pencil"></span> </a> &nbsp &nbsp
                                        <button type="submit" class="btn btn-default btn-sm" onclick="return confirm('Are you sure?')"> <span class="glyphicon glyphicon-trash"></span> </button> 
                                        {!! Form::close() !!}
                                    </td> 
                                </tr>
                                @endif
                            @endforeach

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Guest Name</th>
                                <th>Guest Nic</th>
                                <th>Telephone</th>
                                <th>E-mail</th>                             
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div><!-- /.row -->
</section><!-- /.content -->

<script type="text/javascript" >

    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";

    var slide_bar_element = document.getElementById("guest_menu");
    document.getElementById("guest_menu").className = "active";

</script>

@endsection

resources/views/pages/guest/guest_show.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection

@section('content')



<section class="content-header">
    <h1>Guest  details view <small> page </small></h1>
</section>


<br/>
<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">
            {!! Form::open(['method' => 'DELETE', 'route' => ['guest_page.destroy', $guest->id]]); !!}
            <a href="javascript:history.go(-1)" class="btn btn-default" style='float: right;'> <span class="glyphicon glyphicon-remove-circle"></span> </a>
            <button type="submit" class="btn btn-default" onclick="return confirm('Are you sure?')" style='float: right;'> <span class="glyphicon glyphicon-trash"></span> </button>
            <a href="{!! url('guest_page/'.$guest->id.'/edit') !!}" class="btn btn-default" style='float: right;'> <span class="glyphicon glyphicon-pencil"></span> </a>
            {!! Form::close() !!}

            <br/> <hr/>

            <fieldset>
                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <label>Guest Name : </label>
                        </div> 
                        <div class="col-xs-9">
                            {{ $guest->Name }} 
                        </div>
                    </div>
                </div>
               
                
                <br/>
                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <label>Guest Nic: </label>
                        </div> 
                        <div class="col-xs-9">
                            {{ $guest->nic }} 
                        </div>
                    </div>
                </div>
                
                <br/>
                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <label>Telephone: </label>
                        </div> 
                        <div class="col-xs-9">
                            {{ $guest->telephone }} 
                        </div>
                    </div>
                </div>
                
                
                
                <br/>
                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-3">
                            <label>E-mail: </label>
                        </div> 
                        <div class="col-xs-9">
                            {{ $guest->email }} 
                        </div>
                    </div>
                </div>
                
                
            </fieldset>
        </div>
    </div>
</section>




<script type="text/javascript" >

    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";

    var slide_bar_element = document.getElementById("guest_menu");
    document.getElementById("guest_menu").className = "active";

</script>


@endsection

resources/views/pages/guest/guest_update.blade.php
@extends('layouts.app')

@section('slide_bar')
@include('layouts.home_slide_bar')
@endsection


@section('content')



<section class="content-header">
    <h1>Guest Details Update <small>page </small></h1>
</section><hr/>


<section class='container-fluid'>
    <div class="box box-warning">
        <div class="box-body">

            {!! Form::model($guest ,['method' => 'PATCH','route'=>['guest_page.update',$guest->id]]) !!}

            <fieldset id='myfieldset'>
                <legend> Basic Details </legend>

                <div>
                    <div class="form-group">
                        {!! Form::label('guest_name', 'Guest Name: '); !!}
                        <div class="form-controls">                     
                            {!! Form::text('Name', null, ['class' => 'form-control', 'id' => 'Name', 'placeholder' => 'Enter Guest Name']); !!}
                        </div>
                    </div>


                    <div class="form-group">
                        {!! Form::label('guest_nic', 'NIC :'); !!}
                        <div class="form-controls">                     
                            {!! Form::text('nic', null, ['class' => 'form-control', 'id' => 'nic', 'placeholder' => 'Enter Guest NIC ']); !!}
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset id='myfieldset'>
                <legend> Contact Details </legend>

                <div class="form-group">
                    {!! Form::label('email', 'E-mail: '); !!}
                    <div class="form-controls">
                        {!! Form::email('email', null, ['class' => 'form-control', 'id' => 'id1', 'placeholder' => 'Enter Email Address ']); !!}
                    </div>
                </div>

                <div class='row'>
                    <div class='col-md-4'>
                        <div class="form-group">
                            {!! Form::label('telephone', 'Telephone : '); !!}
                            <div class="form-controls">
                                {!! Form::text('telephone', null, ['class' => 'form-control', 'id' => 'id4', 'placeholder' => 'Telephone ']); !!}
                            </div>
                        </div>
                    </div>
                </div>

            </fieldset> 

            <div class="box-footer">
                <p id='buttons'>
                    {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!} &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
                    {!! Form::reset('Cancel', ['class' => 'btn btn-default']) !!}
                </p>
                {!! Form::close() !!}
            </div>

        </div>
</section>

<script type="text/javascript" >

    var name = document.getElementById("master_entry");
    document.getElementById("master_entry").className = "active";

    var slide_bar_element = document.getElementById("guest_menu");
    document.getElementById("guest_menu").className = "active";

</script>

@endsection